server:
  port: 8085
  servlet:
    context-path: /springCloud
  
spring:
  application:
    name: springCloud

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
#log
logging:
  level:
    com.zj.port.plugin: debug