server:
  port: 8085
  servlet:
    context-path: /
  
spring:
  application:
    name: springCloud
#ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发配置为false,避免重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
#log
logging:
  level:
    com.zj.port.plugin: debug